import { faker } from "@faker-js/faker";

const GENDER = Object.freeze({
  MALE: "Male",
  FEMALE: "Female",
  OTHERS: "Others",
});

const USERS = [
  {
    empId: "EMP0001",
    name: "Prasad Devarakonda",
    designation: "Founder & CEO",
    age: 20,
    joinedOn: "12th June 2016",
    gender: GENDER.MALE,
    bloodGroup: "AB +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Prasad@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0002",
    name: "Kanthu Devarakonda",
    designation: "Managing Director",
    age: 20,
    joinedOn: "12th July 2017",
    gender: GENDER.MALE,
    bloodGroup: "A +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Kanthu@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0003",
    name: "Anil",
    designation: "Deal Hunter",
    age: 20,
    joinedOn: "3rd August 2021",
    gender: GENDER.MALE,
    bloodGroup: "O +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Anil@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0004",
    name: "Wizard",
    designation: "Manager",
    age: 20,
    joinedOn: "3rs September 2017",
    gender: GENDER.MALE,
    bloodGroup: "O +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Wizard@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0005",
    name: "Ravi Chandra Reddy",
    designation: "Content Researcher",
    age: 20,
    joinedOn: "15th October 2020",
    gender: GENDER.MALE,
    bloodGroup: "B -ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Ravi@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0006",
    name: "Ashwin",
    designation: "Content Researcher",
    age: 20,
    joinedOn: "12th February 2023",
    gender: GENDER.MALE,
    bloodGroup: "B +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Ashwin@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0007",
    name: "Pavan",
    designation: "Social Media Manager",
    age: 20,
    joinedOn: "19th May 2022",
    gender: GENDER.MALE,
    bloodGroup: "AB +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Pavan@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0008",
    name: "Nagesh Kumar",
    designation: "Editor/ Visual Effects",
    age: 20,
    joinedOn: "22nd December 2022",
    gender: GENDER.MALE,
    bloodGroup: "AB -ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Nagesh@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0009",
    name: "Tarun",
    designation: "Junior Editor",
    age: 20,
    joinedOn: "12th January 2021",
    gender: GENDER.MALE,
    bloodGroup: "O +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Tarun@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0010",
    name: "Bharath (Donglee)",
    designation: "Senior Editor",
    age: 20,
    joinedOn: "9th May 2017",
    gender: GENDER.MALE,
    bloodGroup: "B +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Bharath@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0011",
    name: "Vamsi Krishna",
    designation: "Senior Editor",
    age: 20,
    joinedOn: "9th May 2017",
    gender: GENDER.MALE,
    bloodGroup: "A +ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Vamsi@pt.com`,
    area: faker.person.jobArea(),
  },
  {
    empId: "EMP0012",
    name: "Ram Charan",
    designation: "Cinematographer",
    age: 20,
    joinedOn: "29th May 2023",
    gender: GENDER.MALE,
    bloodGroup: "A -ve",
    contactNo: faker.phone.number(),
    alternateNo: faker.phone.number(),
    emergency: faker.phone.number(),
    email: `Ram@pt.com`,
    area: faker.person.jobArea(),
  },
];

export { USERS };
