const AUTOMOBILE_CARDS = [
  {
    carName: "Mini Cooper s",
    carId: "PROD000001",
    category: "Car",
    carDetails: {
      receivedOn: new Date(2024, 9, 5),
      shouldBeReturnedOn: new Date(2024, 9, 28),
      isReturned: true,
      isDamaged: false,
      sentByCompany: true,
      embargoTill: null,
      launchPrice: 24000,
      commentsFromCarOwner: "",
    },
    videoDetails: {
      editedBy: ["Anil", "Nagesh Kumar"],
      editingCompletedOn: new Date(),
      thumbnailCreatedBy: ["Vamsi Krishna"],
      approvedByManager: true,
      managerComments: "",
      reviewed: true,
      finalChecks: true,
      cameraSamples: true,
      videoUploaded: true,
      videoPublished: true,
      publishedOn: new Date(),
    },
    created_by: "",
    created_on: new Date(),
  },
  {
    carName: "Range Rover Evoke",
    carId: "PROD000002",
    category: "Car",
    carDetails: {
      receivedOn: new Date(2024, 9, 5),
      shouldBeReturnedOn: new Date(2024, 9, 28),
      isReturned: false,
      isDamaged: false,
      embargoTill: null,
      launchPrice: 24000,
      sentByCompany: true,
      commentsFromCarOwner: "",
    },
    videoDetails: {
      editedBy: ["Anil", "Wizard"],
      editingCompletedOn: new Date(),
      thumbnailCreatedBy: ["Wizard"],
      approvedByManager: false,
      managerComments: "",
      reviewed: true,
      finalChecks: false,
      cameraSamples: false,
      videoUploaded: false,
      videoPublished: false,
      publishedOn: new Date(),
    },
    created_by: "",
    created_on: new Date(),
  },
  {
    carName: "Tata Harrier",
    carId: "PROD000003",
    category: "Car",
    carDetails: {
      receivedOn: new Date(2024, 9, 5),
      shouldBeReturnedOn: new Date(2024, 9, 28),
      isReturned: false,
      isDamaged: false,
      embargoTill: null,
      launchPrice: 24000,
      sentByCompany: true,
      commentsFromCarOwner: "",
    },
    videoDetails: {
      editedBy: ["Anil", "Wizard"],
      editingCompletedOn: new Date(),
      thumbnailCreatedBy: ["Wizard"],
      approvedByManager: false,
      managerComments: "",
      reviewed: true,
      finalChecks: false,
      cameraSamples: false,
      videoUploaded: false,
      videoPublished: false,
      publishedOn: new Date(),
    },
    created_by: "",
    created_on: new Date(),
  },
];

export { AUTOMOBILE_CARDS };
