const MOBILE_CARDS = [
  {
    productName: "Redmi 13 Pro",
    productId: "PROD000001",
    category: "Mobiles",
    productDetails: {
      receivedOn: new Date(2024, 9, 5),
      shouldBeReturnedOn: new Date(2024, 9, 28),
      isReturned: false,
      isDamaged: false,
      sentByCompany: true,
      embargoTill: null,
      launchPrice: 24000,
      commentsFromProductOwner: "",
    },
    videoDetails: {
      editedBy: ["Anil", "Nagesh Kumar"],
      editingCompletedOn: new Date(),
      thumbnailCreatedBy: ["Vamsi Krishna"],
      approvedByManager: true,
      managerComments: "",
      unboxed: true,
      reviewed: true,
      finalChecks: true,
      cameraSamples: true,
      videoUploaded: true,
      videoPublished: true,
      publishedOn: new Date(),
    },
    created_by: "",
    created_on: new Date(),
  },
  {
    productName: "Redmi 12 Pro",
    productId: "PROD000001",
    category: "Mobiles",
    productDetails: {
      receivedOn: new Date(2024, 9, 5),
      shouldBeReturnedOn: new Date(2024, 9, 28),
      isReturned: false,
      isDamaged: false,
      embargoTill: null,
      launchPrice: 24000,
      sentByCompany: true,
      commentsFromProductOwner: "",
    },
    videoDetails: {
      editedBy: ["Anil", "Wizard"],
      editingCompletedOn: new Date(),
      thumbnailCreatedBy: ["Wizard"],
      approvedByManager: false,
      managerComments: "",
      unboxed: true,
      reviewed: false,
      finalChecks: false,
      cameraSamples: false,
      videoUploaded: false,
      videoPublished: false,
      publishedOn: new Date(),
    },
    created_by: "",
    created_on: new Date(),
  },
];

export { MOBILE_CARDS };
