import {
  CAR_ICON,
  FUND_ANALYSIS_ICON,
  FUND_INSIGHTS_ICON,
  FUND_REVIEW_ICON,
  GAME_ICON,
  HOME_ICON,
  LIFESTYLE_ICON,
  MARKET_OUTLOOK_ICON,
  MOBILE_ICON,
  SETTINGS_ICON,
  TASKS_ICON,
  TRIPS_ICON,
  USERS_ICON,
} from "../constants/icons";

const SIDE_NAV_ITEMS = [
  {
    name: "Home",
    url: "home",
    key: "",
    openInNewTab: false,
    icon: HOME_ICON,
    tooltip: "Home",
  },
  {
    name: "Tasks",
    url: "tasks",
    key: "",
    openInNewTab: false,
    icon: TASKS_ICON,
    tooltip: "Tasks",
  },
  {
    name: "Mobiles",
    url: "mobiles",
    key: "",
    openInNewTab: false,
    icon: MOBILE_ICON,
    tooltip:
      "Technology , Smartphone Reviews , Unboxing Gadgets , Electronics , Gadget Reviews, Tech videos, Tech Q&A , Technews",
  },
  {
    name: "Lifestyle",
    url: "lifestyle",
    key: "",
    openInNewTab: false,
    icon: LIFESTYLE_ICON,
    tooltip: "Lifestyle",
  },
  {
    name: "Automobiles",
    url: "automobiles",
    key: "",
    openInNewTab: false,
    icon: CAR_ICON,
    tooltip: "Automobiles",
  },
  {
    name: "Gaming",
    url: "gaming",
    key: "",
    openInNewTab: false,
    icon: GAME_ICON,
    tooltip: "Gaming",
  },
  {
    name: "Employees",
    url: "employees",
    key: "",
    openInNewTab: false,
    icon: USERS_ICON,
    tooltip: "Employees",
  },
  {
    name: "Trips",
    url: "trips",
    key: "",
    openInNewTab: false,
    icon: TRIPS_ICON,
    tooltip: "Employees",
  },
  {
    name: "Settings",
    url: "settings",
    key: "settings",
    openInNewTab: false,
    icon: SETTINGS_ICON,
    tooltip: "Settings",
  },
];

export { SIDE_NAV_ITEMS };
