import { BLOOD_GROUP_ICON, CITY_ICON, COUNTRY_ICON, CURRENCY_ICON, DOC_ADD_ICON, DOC_DEPT_ICON, DOC_DESIGNATION_ICON, DOC_SPECIALITY_ICON, DOC_TYPES_ICON, GENDER_ICON, ID_TYPE_ICON, LANGUAGE_ICON, MARITAL_STATUS_ICON, NATIONALITY_ICON, NEXT_OF_KIN_ICON, PATIENT_CATEGORY_ICON, PATIENT_TYPE_ICON, SALUTATION_ICON, STATE_ICON, RELIGION_ICON, BANK_ICON, PAYMENT_TYPE_ICON, DOC_DEGREE_ICON, USERS_ICON, ROLES_ICON } from "../../constants/icons";





const COMMON_MASTER_MENU = [
  {
    name: "Blood Group",
    url: null,
    isDialog: true,
    uniqueName: "BLOOD_GROUP",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: BLOOD_GROUP_ICON,
    hideAddBtn: true,
  },
  {
    name: "Gender",
    url: null,
    isDialog: true,
    uniqueName: "GENDER",
    apiEndPoint: "/masters/gender",
    openInNewTab: false,
    icon: GENDER_ICON,
    hideAddBtn: false,
  },
  {
    name: "Marital Status",
    url: null,
    isDialog: true,
    uniqueName: "MARITAL_STATUS",
    apiEndPoint: "/masters/maritalStatus",
    openInNewTab: false,
    icon: MARITAL_STATUS_ICON,
    hideAddBtn: false,
  },
  {
    name: "Salutation",
    url: null,
    isDialog: true,
    uniqueName: "SALUTATION",
    apiEndPoint: "/masters/salutation",
    openInNewTab: false,
    icon: SALUTATION_ICON,
    hideAddBtn: false,
  },
  {
    name: "Relation",
    url: null,
    isDialog: true,
    uniqueName: "RELATION",
    apiEndPoint: "/masters/relation",
    openInNewTab: false,
    icon: NEXT_OF_KIN_ICON,
    hideAddBtn: false,
  },
  {
    name: "Language",
    url: null,
    isDialog: true,
    uniqueName: "LANGUAGE",
    apiEndPoint: "/masters/language",
    openInNewTab: false,
    icon: LANGUAGE_ICON,
    hideAddBtn: false,
  },
  {
    name: "City",
    url: null,
    isDialog: true,
    uniqueName: "CITY",
    apiEndPoint: "/masters/city",
    openInNewTab: false,
    icon: CITY_ICON,
    hideAddBtn: false,
  },
  {
    name: "State",
    url: null,
    isDialog: true,
    uniqueName: "STATE",
    apiEndPoint: "/masters/state",
    openInNewTab: false,
    icon: STATE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Country",
    url: null,
    isDialog: true,
    uniqueName: "COUNTRY",
    apiEndPoint: "/masters/country",
    openInNewTab: false,
    icon: COUNTRY_ICON,
    hideAddBtn: false,
  },
  {
    name: "Nationality",
    url: null,
    isDialog: true,
    uniqueName: "NATIONALITY",
    apiEndPoint: "/masters/nationality",
    openInNewTab: false,
    icon: NATIONALITY_ICON,
    hideAddBtn: false,
  },
  {
    name: "Identity Type",
    url: null,
    isDialog: true,
    uniqueName: "IDENTITY_TYPE",
    apiEndPoint: "/masters/identityType",
    openInNewTab: false,
    icon: ID_TYPE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Patient Type",
    url: null,
    isDialog: true,
    uniqueName: "PATIENT_TYPE",
    apiEndPoint: "/masters/patientType",
    openInNewTab: false,
    icon: PATIENT_TYPE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Patient Category",
    url: null,
    isDialog: true,
    uniqueName: "PATIENT_CATEGORY",
    apiEndPoint: "/masters/patientCategory",
    openInNewTab: false,
    icon: PATIENT_CATEGORY_ICON,
    hideAddBtn: false,
  },
  {
    name: "Religion",
    url: null,
    isDialog: true,
    uniqueName: "RELIGION",
    apiEndPoint: "/masters/religion",
    openInNewTab: false,
    icon: RELIGION_ICON,
    hideAddBtn: false,
  },
  {
    name: "Bank",
    url: null,
    isDialog: true,
    uniqueName: "BANK",
    apiEndPoint: "/masters/bank",
    openInNewTab: false,
    icon: BANK_ICON,
    hideAddBtn: false,
  },
  {
    name: "Payment Type",
    url: null,
    isDialog: true,
    uniqueName: "PAYMENT_TYPE",
    apiEndPoint: "/masters/paymentType",
    openInNewTab: false,
    icon: PAYMENT_TYPE_ICON,
    hideAddBtn: false,
  },
];


const DOCTOR_MASTER_MENU = [
  {
    name: "Speciality",
    url: null,
    isDialog: true,
    uniqueName: "DOC_SPECIALITY",
    apiEndPoint: "/masters/docSpeciality",
    openInNewTab: false,
    icon: DOC_SPECIALITY_ICON,
    hideAddBtn: false,
  },
  {
    name: "Degrees",
    url: null,
    isDialog: true,
    uniqueName: "DOC_DEGREE",
    apiEndPoint: "/masters/docDegree",
    openInNewTab: false,
    icon: DOC_DEGREE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Doctor",
    url: null,
    isDialog: true,
    uniqueName: "ADD_DOCTOR",
    apiEndPoint: "/masters/doctor",
    openInNewTab: false,
    icon: DOC_ADD_ICON,
    hideAddBtn: false,
  },
  // {
  //   name: "Doctor Type",
  //   url: null,
  //   isDialog: true,
  //   uniqueName: "DOCTOR_TYPE",
  //   apiEndPoint: "/masters/bloodGroup",
  //   openInNewTab: false,
  //   icon: DOC_TYPES_ICON,
  //   hideAddBtn: false,
  // },
];

const ROLES_USERS_MASTER_MENU = [
  {
    name: "Users",
    url: null,
    isDialog: true,
    uniqueName: "USERS",
    apiEndPoint: "/users",
    openInNewTab: false,
    icon: USERS_ICON,
    hideAddBtn: false,
  },
  {
    name: "Roles",
    url: null,
    isDialog: true,
    uniqueName: "USER_ROLES",
    apiEndPoint: "/users/roles",
    openInNewTab: false,
    icon: ROLES_ICON,
    hideAddBtn: true,
  },
];

export { COMMON_MASTER_MENU, DOCTOR_MASTER_MENU, ROLES_USERS_MASTER_MENU };
