import { BLOOD_GROUP_ICON, CITY_ICON, COUNTRY_ICON, CURRENCY_ICON, DOC_ADD_ICON, DOC_DEPT_ICON, DOC_DESIGNATION_ICON, DOC_SPECIALITY_ICON, DOC_TYPES_ICON, GENDER_ICON, LANGUAGE_ICON, MARITAL_STATUS_ICON, NEXT_OF_KIN_ICON, SALUTATION_ICON, STATE_ICON } from "../../constants/icons";





const COMMON_MASTER_MENU = [
  {
    name: "Blood Group",
    url: null,
    isDialog: true,
    uniqueName: "BLOOD_GROUP",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: BLOOD_GROUP_ICON,
    hideAddBtn: true,
  },
  {
    name: "Gender",
    url: null,
    isDialog: true,
    uniqueName: "GENDER",
    apiEndPoint: "/masters/gender",
    openInNewTab: false,
    icon: GENDER_ICON,
    hideAddBtn: false,
  },
  {
    name: "Marital Status",
    url: null,
    isDialog: true,
    uniqueName: "MARITAL_STATUS",
    apiEndPoint: "/masters/maritalStatus",
    openInNewTab: false,
    icon: MARITAL_STATUS_ICON,
    hideAddBtn: false,
  },
  {
    name: "Salutation",
    url: null,
    isDialog: true,
    uniqueName: "SALUTATION",
    apiEndPoint: "/masters/salutation",
    openInNewTab: false,
    icon: SALUTATION_ICON,
    hideAddBtn: false,
  },
  {
    name: "Relation",
    url: null,
    isDialog: true,
    uniqueName: "RELATION",
    apiEndPoint: "/masters/relation",
    openInNewTab: false,
    icon: NEXT_OF_KIN_ICON,
    hideAddBtn: false,
  },
  {
    name: "Language",
    url: null,
    isDialog: true,
    uniqueName: "LANGUAGE",
    apiEndPoint: "/masters/language",
    openInNewTab: false,
    icon: LANGUAGE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Currency",
    url: null,
    isDialog: true,
    uniqueName: "CURRENCY",
    apiEndPoint: "/masters/nextOfKin",
    openInNewTab: false,
    icon: CURRENCY_ICON,
    hideAddBtn: false,
  },
  {
    name: "City",
    url: null,
    isDialog: true,
    uniqueName: "CITY",
    apiEndPoint: "/masters/city",
    openInNewTab: false,
    icon: CITY_ICON,
    hideAddBtn: false,
  },
  {
    name: "State",
    url: null,
    isDialog: true,
    uniqueName: "STATE",
    apiEndPoint: "/masters/state",
    openInNewTab: false,
    icon: STATE_ICON,
    hideAddBtn: false,
  },
  {
    name: "Country",
    url: null,
    isDialog: true,
    uniqueName: "COUNTRY",
    apiEndPoint: "/masters/country",
    openInNewTab: false,
    icon: COUNTRY_ICON,
    hideAddBtn: false,
  },
];


const DOCTOR_MASTER_MENU = [
  {
    name: "Speciality",
    url: null,
    isDialog: true,
    uniqueName: "SPECIALITY",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: DOC_SPECIALITY_ICON,
    hideAddBtn: true,
  },
  {
    name: "Department",
    url: null,
    isDialog: true,
    uniqueName: "DEPARTMENT",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: DOC_DEPT_ICON,
    hideAddBtn: true,
  },
  {
    name: "Designation",
    url: null,
    isDialog: true,
    uniqueName: "DESIGNATION",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: DOC_DESIGNATION_ICON,
    hideAddBtn: true,
  },
  {
    name: "Add Doctor",
    url: null,
    isDialog: true,
    uniqueName: "ADD_DOCTOR",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: DOC_ADD_ICON,
    hideAddBtn: true,
  },
  {
    name: "Doctor Type",
    url: null,
    isDialog: true,
    uniqueName: "DOCTOR_TYPE",
    apiEndPoint: "/masters/bloodGroup",
    openInNewTab: false,
    icon: DOC_TYPES_ICON,
    hideAddBtn: true,
  },
];

export { COMMON_MASTER_MENU, DOCTOR_MASTER_MENU };
